language: python
python:
    - "2.7"
cache: apt
install:
    - "pip install -r requirements.txt"
script:
    - "pelican  -o output content -s publishconf.py --theme-path pelican-bootstrap3/ -v"
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
      secret_access_key: $AWS_SECRET_KEY
      bucket: tdhopper.com
      endpoint: tdhopper.com.s3-website-us-east-1.amazonaws.com
      region: us-east-1
      skip_cleanup: true
      local-dir: output
      acl: public_read
      default_text_charset: 'utf-8' 
      detect_encoding: true
      on:
        branch: master
notifications:
    email: false
